

name: A

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      my_input_param:
        description: 'My input parameter'
        required: true
env:
  ENVIRONMENT: "initial_value"
jobs:
  actionA:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

 
    steps:
    - name: Change Variable Value
      run: echo "ENV_DATA= Staging" >> $GITHUB_ENV

 
