

name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  trigger-action-d:
    runs-on: ubuntu-latest
    steps:
    
    - name: Trigger Action D
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: LapusteAlexandru/PP
        event-type: run-action-d
