

name: A

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      my_input_param:
        description: 'My input parameter'
        required: true
jobs:
  actionA:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Set Output Value
        id: set_output
        run: echo "::set-output name=ENVIRONMENT::Sage"
      
      - name: Display Output Value
        run: echo "Output value:" ${{ steps.set_output.outputs.ENVIRONMENT }}
      - name: Trigger Action B
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: LapusteAlexandru/PP
          event-type: get_env
          client-payload: |
            {
              "Env": "${{ steps.set_output.outputs.ENVIRONMENT }}"
            }
