

name: A

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      my_input_param:
        description: 'My input parameter'
        required: true

jobs:
  actionA:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

   
    steps:
    - name: Set Variable
      run: echo "::set-output name=myVariable::someValue"
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myArtifact
        path: ${{ github.workspace }}

 
