

name: A

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      my_input_param:
        description: 'My input parameter'
        required: true
env:
  ENV_DATA: "initial_value"
jobs:
  actionA:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

 
    steps:
      - name: Set Output Value
        id: set_output
        run: echo "::set-output name=myOutput::Stage"
 
