name: Trigger B
on:
  workflow_run:
    workflows: ["A"]
    types:
      - completed
env:
  ENV: "initial_value"
jobs:
  trigger-action-d:
    runs-on: ubuntu-latest
    steps:
    
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        name: my-artifact
        
    - name: Read Variable Value
      run: |
        value=$(cat variable.txt)
        echo "ENV=$value" >> $GITHUB_ENV
        
    - name: Trigger Action B
      uses: peter-evans/repository-dispatch@v1x
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: LapusteAlexandru/PP
        event-type: run-action-d
        run: |
          value=$(cat variable.txt)
        client-payload: |
          {
            "Env": "${{ env.ENV }}"
          }
