name: Trigger B
on:
  workflow_run:
    workflows: ["A"]
    types:
      - completed
jobs:
  trigger-action-d:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        name: my-artifact
    - name: Read Variable Value
      id: read-variable
      run: |
        echo "::set-output name=deploy::$(cat variable.txt)"
    - name: Trigger Action B
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: LapusteAlexandru/PP
        event-type: run-action-d
        client-payload: |
          {
            "env": "${{ steps.read-variable.outputs.deploy }}"
          }
