name: Trigger B
on:
  workflow_run:
    workflows: ["A"]
    types:
      - completed

jobs:
  trigger-action-d:
    runs-on: ubuntu-latest
    steps:
    
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ./path/to/artifact
        
    - name: Read Variable Value
      run: |
        value=$(cat variable.txt)
        echo "Variable Value: $value"
        
    - name: Trigger Action B
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: LapusteAlexandru/PP
        event-type: run-action-d
        client-payload: |
          {
            "Env": $(cat variable.txt)
          }
